Type orm
hugoblanc/node-template pull request #3
Opened 2020-02-29 14:49 UTC by Paul-D-Dev

2020-02-29 14:49 UTC, Paul-D-Dev commented
Ajout du core avec Abstract service et common function

2020-03-08 15:29 UTC, hugoblanc approved these changes
Tout cela me semble valide ! Bien joué

2020-03-08 15:31 UTC, hugoblanc requested changes
Malheureusement il y a des conflits :(

>package-lock.json
package.json
src/controller/user.controller.ts
src/entity/user.entity.ts
src/index.ts
src/loaders/express.ts
src/loaders/index.ts
src/loaders/typeorm.ts
src/repository/user.repository.ts
src/services/user.service.ts
tsconfig.json

2020-03-23 10:48 UTC, Paul-D-Dev commented
J'ai résolu les conflits, est-ce qu'il y a possibilité de tester la version avant de merger pour voir si tout fonctionne correctement ?

2020-03-26 14:09 UTC, hugoblanc commented
Bravo !

2020-03-26 14:09 UTC, merged

2020-03-26 14:10 UTC, hugoblanc commented
Mais j'ai pas testé